openapi: '3.0.2'
info:
  title: Inventory Management Auth API
  version: '1.0.0'
servers:
  - url: http://inventory-management.com/api/auth
paths:
  /sign-in:
    get:
      responses:
        '200':
          description: OK
